/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Perro.glb -o src/Perro.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Perro.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.torso.geometry} material={nodes.torso.material} position={[0.012, 0.728, -0.33]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.FL_hip.geometry} material={nodes.FL_hip.material} position={[0.132, 0.524, -0.015]}>
          <mesh geometry={nodes.FL_thigh.geometry} material={nodes.FL_thigh.material} position={[0.081, 0.002, -0.012]}>
            <mesh geometry={nodes.FL_calf.geometry} material={nodes.FL_calf.material} position={[0.003, 0.014, 0.352]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.FR_hip.geometry} material={nodes.FR_hip.material} position={[-0.166, 0.542, -0.011]}>
          <mesh geometry={nodes.FR_thigh.geometry} material={nodes.FR_thigh.material} position={[-0.073, -0.015, -0.015]}>
            <mesh geometry={nodes.FR_calf.geometry} material={nodes.FR_calf.material} position={[-0.002, 0.017, 0.35]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.RL_hip.geometry} material={nodes.RL_hip.material} position={[0.146, 0.016, -0.003]}>
          <mesh geometry={nodes.RL_thigh.geometry} material={nodes.RL_thigh.material} position={[-0.158, 0.314, 0.731]}>
            <mesh geometry={nodes.RL_calf.geometry} material={nodes.RL_calf.material} position={[0.23, -0.315, -0.41]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.RR_hip.geometry} material={nodes.RR_hip.material} position={[-0.165, -0.006, 0.002]}>
          <mesh geometry={nodes.RR_thigh.geometry} material={nodes.RR_thigh.material} position={[-0.072, 0.025, -0.018]}>
            <mesh geometry={nodes.RR_calf.geometry} material={nodes.RR_calf.material} position={[-0.006, -0.004, 0.342]} />
          </mesh>
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Perro.glb')
